# Site settings
title: Mia Allers Design
description: "The portfolio site of Mia Allers"
url: "http://miakepia.github.io/nav-test"
tagline: A case study

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
# paginate: 4
# paginate_path: '/blog/page:num/'
# permalink: /blog/:title
